[variables]
RAILS_ENV = "production"
BUNDLE_WITHOUT = "development:test"

[phases.setup]
nixPkgs = ["postgresql"]

[phases.install]
cmd = "bundle install"

[phases.build]
cmd = "bundle exec rails assets:precompile"

[phases.start]
cmd = "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT"
