[variables]
NIXPACKS_PATH = "/app"

[phases.setup]
nixPkgs = ['ruby']

[phases.install]
cmds = [
    'ls -la',
    'cp -r backend/* . || echo "Copy failed"',
    'ls -la',
    'bundle install --deployment --without development test'
]

[start]
cmd = "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT"
