[build]
builder = "NIXPACKS"
buildCommand = "cd backend && bundle install && bundle exec rails assets:precompile"

[deploy]
startCommand = "cd backend && bundle exec rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { RAILS_ENV = "production" }
