[build]
builder = "NIXPACKS"
buildCommand = "bundle install"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec rails server"
healthcheckPath = "/health"

[environments.production]
variables = { RAILS_ENV = "production" }
