[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && bundle exec rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/health"

[environments.production]
variables = { RAILS_ENV = "production" }
